### ISSUE TITLE
大神我也可以加入麼

### ISSUE THREAD

**Issue by HenryQuan** [splitline/emina-one#4]
大神的這個App感覺比我的要好很多。不僅可以保存歷史記錄還可以收藏動畫，連密碼都可以直接跳過（可以的話，可以直接搬回來用麼），播放器也比 Flutter 的這個要好很多， React Native 還是有很多優勢的。我也會使用 React Native 的但是明顯不如大神這麼厲害，可以的話我也可以做一些 pull request。

**Comment by splitline** [comment]
目前還是有很多功能沒有完善或是有 bug，當然歡迎自行發 PR 呀

播放器的部分，那些功能 / UI 都是我自己純手刻的，只有用了最基礎的 Video component，本來不想這麼麻煩的，但發現好像沒有一個現成的播放器能合我胃口 XD


密碼驗證的部分，其實該網站只需要簡單的帶上一個 cookie （忘記名字，手邊沒電腦晚點補）就能繞過驗證了，但受限於 RN 的原生功能（也懶得自己寫 native module）而不能直接設定 cookie，所以我還是多自行模擬了 post password 的請求。因此我的寫法應該不是最佳解，可以不用抄(?

不過我其實覺得 Flutter 效能上比 React Native 好一些，而且 material design 的 UI 也做的比較漂亮，可惜我一直不習慣他的語法 XD

**Comment by HenryQuan** [comment]
原來播放器這麼厲害啊，我都是用別人的，我也是說 React Native 哪裡有這麼好的播放器啊，可以考慮做個 package。話說全部的視頻都可以使用 video component 來播放麼？我的那裡有的是不可以的。
密碼驗證的話，我目前打算就是用cookie來通過瀏覽器檢查和密碼輸使入。原生這邊都已經些好了，但是網站很久沒有檢查瀏覽器了而且我這邊也不需要輸入密碼所以進度緩慢。

**Comment by splitline** [comment]
看起來你是 mp4 的沒辦法支援嘛？
因為它的設計存取 mp4 需要帶 cookie，不然會 403，你使用的套件預設存取 remote video 似乎不會帶上 cookie

**Comment by HenryQuan** [comment]
@splitline 大神新年快樂，anime1網站重新上線了。有沒有打算繼續更新？ 我發現我的舊版AnimeOne還是可以繼續使用的。
